/* ES2 Hero Studio Web Beta 0.4.0-beta.13 */
const CACHE_NAME = "es2-hero-studio-web-0.4.0-beta.13-5104182d0af290ce";
const PRECACHE_URLS = [
  "./",
  "./.DS_Store",
  "./apple-touch-icon.png",
  "./assets/AssetStudio-CSdjPDlT.css",
  "./assets/AssetStudio-dVaJPVn1.js",
  "./assets/SkillTreeEditor-BbA7e7Ue.css",
  "./assets/SkillTreeEditor-BnxUIR9C.js",
  "./assets/XMLPreview-CK7IxAho.css",
  "./assets/XMLPreview-DVNUX2aI.js",
  "./assets/archive-tools-DbCH7d_d.js",
  "./assets/codicon-DCmgc-ay.ttf",
  "./assets/index-4VRr95gK.js",
  "./assets/index-KrEYmef3.css",
  "./assets/index-Zl_ShPI6.css",
  "./assets/index-yDmtwnYV.js",
  "./assets/react-vendor-CHVyg34E.js",
  "./assets/skill-tree-canvas-B5DZHykP.css",
  "./assets/skill-tree-canvas-fS4bxG5F.js",
  "./assets/xml-editor-B_tlCceW.js",
  "./assets/xml-editor-D4zjdeIP.css",
  "./demo/Airiam.zip",
  "./favicon-16x16.png",
  "./favicon-32x32.png",
  "./favicon.ico",
  "./help/artwork-requirement-guidance.html",
  "./help/assets/help.css",
  "./help/assets/icon-192.png",
  "./help/assets/icon-32.png",
  "./help/browser-beta.html",
  "./help/documentation-manifest.json",
  "./help/es2-skill-catalog.html",
  "./help/feedback.html",
  "./help/getting-started.html",
  "./help/github-release.html",
  "./help/guided-creation.html",
  "./help/guided-gameplay.html",
  "./help/import-xml.html",
  "./help/index.html",
  "./help/installation.html",
  "./help/keyboard-accessibility.html",
  "./help/known-limitations.html",
  "./help/localization-dependencies.html",
  "./help/modes.html",
  "./help/privacy.html",
  "./help/recovery.html",
  "./help/relationship-aware-recommendations.html",
  "./help/release-export.html",
  "./help/release-notes-4-0f.html",
  "./help/release-notes-4-0g.html",
  "./help/release-notes-4-0h.html",
  "./help/release-notes-4-0i.html",
  "./help/release-notes-4-0j.html",
  "./help/release-notes-4-0k.html",
  "./help/release-notes-4-0l.html",
  "./help/release-notes-4-0m.html",
  "./help/release-notes.html",
  "./help/skill-tree-progression-guidance.html",
  "./help/starter-hero-structures.html",
  "./help/templates-guidance.html",
  "./help/troubleshooting.html",
  "./help/user-guide.html",
  "./help/web-deployment.html",
  "./help/web-release-notes.html",
  "./icon-192.png",
  "./icon-512.png",
  "./icon.svg",
  "./index.html",
  "./manifest.webmanifest",
  "./maskable-icon-512.png",
  "./monaco/.DS_Store",
  "./monaco/vs/.DS_Store",
  "./monaco/vs/base/browser/ui/codicons/codicon/codicon.ttf",
  "./monaco/vs/base/worker/workerMain.js",
  "./monaco/vs/basic-languages/abap/abap.js",
  "./monaco/vs/basic-languages/apex/apex.js",
  "./monaco/vs/basic-languages/azcli/azcli.js",
  "./monaco/vs/basic-languages/bat/bat.js",
  "./monaco/vs/basic-languages/bicep/bicep.js",
  "./monaco/vs/basic-languages/cameligo/cameligo.js",
  "./monaco/vs/basic-languages/clojure/clojure.js",
  "./monaco/vs/basic-languages/coffee/coffee.js",
  "./monaco/vs/basic-languages/cpp/cpp.js",
  "./monaco/vs/basic-languages/csharp/csharp.js",
  "./monaco/vs/basic-languages/csp/csp.js",
  "./monaco/vs/basic-languages/css/css.js",
  "./monaco/vs/basic-languages/cypher/cypher.js",
  "./monaco/vs/basic-languages/dart/dart.js",
  "./monaco/vs/basic-languages/dockerfile/dockerfile.js",
  "./monaco/vs/basic-languages/ecl/ecl.js",
  "./monaco/vs/basic-languages/elixir/elixir.js",
  "./monaco/vs/basic-languages/flow9/flow9.js",
  "./monaco/vs/basic-languages/freemarker2/freemarker2.js",
  "./monaco/vs/basic-languages/fsharp/fsharp.js",
  "./monaco/vs/basic-languages/go/go.js",
  "./monaco/vs/basic-languages/graphql/graphql.js",
  "./monaco/vs/basic-languages/handlebars/handlebars.js",
  "./monaco/vs/basic-languages/hcl/hcl.js",
  "./monaco/vs/basic-languages/html/html.js",
  "./monaco/vs/basic-languages/ini/ini.js",
  "./monaco/vs/basic-languages/java/java.js",
  "./monaco/vs/basic-languages/javascript/javascript.js",
  "./monaco/vs/basic-languages/julia/julia.js",
  "./monaco/vs/basic-languages/kotlin/kotlin.js",
  "./monaco/vs/basic-languages/less/less.js",
  "./monaco/vs/basic-languages/lexon/lexon.js",
  "./monaco/vs/basic-languages/liquid/liquid.js",
  "./monaco/vs/basic-languages/lua/lua.js",
  "./monaco/vs/basic-languages/m3/m3.js",
  "./monaco/vs/basic-languages/markdown/markdown.js",
  "./monaco/vs/basic-languages/mdx/mdx.js",
  "./monaco/vs/basic-languages/mips/mips.js",
  "./monaco/vs/basic-languages/msdax/msdax.js",
  "./monaco/vs/basic-languages/mysql/mysql.js",
  "./monaco/vs/basic-languages/objective-c/objective-c.js",
  "./monaco/vs/basic-languages/pascal/pascal.js",
  "./monaco/vs/basic-languages/pascaligo/pascaligo.js",
  "./monaco/vs/basic-languages/perl/perl.js",
  "./monaco/vs/basic-languages/pgsql/pgsql.js",
  "./monaco/vs/basic-languages/php/php.js",
  "./monaco/vs/basic-languages/pla/pla.js",
  "./monaco/vs/basic-languages/postiats/postiats.js",
  "./monaco/vs/basic-languages/powerquery/powerquery.js",
  "./monaco/vs/basic-languages/powershell/powershell.js",
  "./monaco/vs/basic-languages/protobuf/protobuf.js",
  "./monaco/vs/basic-languages/pug/pug.js",
  "./monaco/vs/basic-languages/python/python.js",
  "./monaco/vs/basic-languages/qsharp/qsharp.js",
  "./monaco/vs/basic-languages/r/r.js",
  "./monaco/vs/basic-languages/razor/razor.js",
  "./monaco/vs/basic-languages/redis/redis.js",
  "./monaco/vs/basic-languages/redshift/redshift.js",
  "./monaco/vs/basic-languages/restructuredtext/restructuredtext.js",
  "./monaco/vs/basic-languages/ruby/ruby.js",
  "./monaco/vs/basic-languages/rust/rust.js",
  "./monaco/vs/basic-languages/sb/sb.js",
  "./monaco/vs/basic-languages/scala/scala.js",
  "./monaco/vs/basic-languages/scheme/scheme.js",
  "./monaco/vs/basic-languages/scss/scss.js",
  "./monaco/vs/basic-languages/shell/shell.js",
  "./monaco/vs/basic-languages/solidity/solidity.js",
  "./monaco/vs/basic-languages/sophia/sophia.js",
  "./monaco/vs/basic-languages/sparql/sparql.js",
  "./monaco/vs/basic-languages/sql/sql.js",
  "./monaco/vs/basic-languages/st/st.js",
  "./monaco/vs/basic-languages/swift/swift.js",
  "./monaco/vs/basic-languages/systemverilog/systemverilog.js",
  "./monaco/vs/basic-languages/tcl/tcl.js",
  "./monaco/vs/basic-languages/twig/twig.js",
  "./monaco/vs/basic-languages/typescript/typescript.js",
  "./monaco/vs/basic-languages/typespec/typespec.js",
  "./monaco/vs/basic-languages/vb/vb.js",
  "./monaco/vs/basic-languages/wgsl/wgsl.js",
  "./monaco/vs/basic-languages/xml/xml.js",
  "./monaco/vs/basic-languages/yaml/yaml.js",
  "./monaco/vs/editor/editor.main.css",
  "./monaco/vs/editor/editor.main.js",
  "./monaco/vs/language/css/cssMode.js",
  "./monaco/vs/language/css/cssWorker.js",
  "./monaco/vs/language/html/htmlMode.js",
  "./monaco/vs/language/html/htmlWorker.js",
  "./monaco/vs/language/json/jsonMode.js",
  "./monaco/vs/language/json/jsonWorker.js",
  "./monaco/vs/language/typescript/tsMode.js",
  "./monaco/vs/language/typescript/tsWorker.js",
  "./monaco/vs/loader.js",
  "./monaco/vs/nls.messages.de.js",
  "./monaco/vs/nls.messages.es.js",
  "./monaco/vs/nls.messages.fr.js",
  "./monaco/vs/nls.messages.it.js",
  "./monaco/vs/nls.messages.ja.js",
  "./monaco/vs/nls.messages.ko.js",
  "./monaco/vs/nls.messages.ru.js",
  "./monaco/vs/nls.messages.zh-cn.js",
  "./monaco/vs/nls.messages.zh-tw.js"
];
self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS)).then(() => self.skipWaiting()));
});
self.addEventListener("activate", (event) => {
  event.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((key) => key.startsWith("es2-hero-studio-web-") && key !== CACHE_NAME).map((key) => caches.delete(key)))).then(() => self.clients.claim()));
});
self.addEventListener("message", (event) => {
  if (event.data?.type === "SKIP_WAITING") self.skipWaiting();
});
self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (request.mode === "navigate") {
    event.respondWith(fetch(request).then((response) => {
      const copy = response.clone();
      caches.open(CACHE_NAME).then((cache) => cache.put("./index.html", copy));
      return response;
    }).catch(() => caches.match("./index.html").then((response) => response || caches.match("./"))));
    return;
  }
  event.respondWith(caches.match(request).then((cached) => cached || fetch(request).then((response) => {
    if (response.ok) caches.open(CACHE_NAME).then((cache) => cache.put(request, response.clone()));
    return response;
  })));
});
